# Generated by Django 5.1.1 on 2024-10-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estado',
            field=models.CharField(max_length=100, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='task',
            name='pais',
            field=models.CharField(max_length=100, null=True, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dateCompleted',
            field=models.DateTimeField(null=True, verbose_name='Fecha terminado'),
        ),
    ]
